import streamlit as st
import subprocess
import sys
import os
import json # Added for JSON handling if needed, though mostly handled by file read

# --- Page Configuration ---
st.set_page_config(
    page_title="SAE Test Flight 1",
    page_icon="✈️",
    layout="wide"
)

# --- Header ---
st.title("✈️ SAE Test Flight 1")
st.markdown("### SAE Test Security Architecture Review Automation Center")
st.markdown("---")

# --- Function to Execute Scripts ---
def run_script(script_name):
    """
    Runs a python script using subprocess and captures the output.
    """
    # Check if file exists first
    if not os.path.exists(script_name):
        st.error(f"❌ File not found: {script_name}")
        st.warning(f"Make sure {script_name} is in the same folder as this dashboard.")
        return

    with st.spinner(f"Running {script_name}... (Please wait)"):
        try:
            # Using sys.executable ensures we use the same python environment
            result = subprocess.run(
                [sys.executable, script_name],
                capture_output=True,
                text=True,
                check=False
            )
            
            # Display Standard Output
            if result.stdout:
                st.success(f"✅ Execution of {script_name} complete.")
                st.code(result.stdout, language="text")
            
            # Display Errors (if any)
            if result.stderr:
                st.error("⚠️ Errors/Warnings detected:")
                st.code(result.stderr, language="text")

        except Exception as e:
            st.error(f"An error occurred while trying to run the script: {e}")

# --- Sidebar Controls ---
st.sidebar.header("Mission Controls")
st.sidebar.info("Select a module below to execute.")

# --- Main Interface ---

# Create columns for a grid layout
col1, col2 = st.columns(2)

# ================= COLUMN 1 =================
with col1:
    st.subheader("🛡️ Security Audits")
    
    # Button for the "Master" Audit (SAEtestaudit2.py)
    if st.button("Run Full Security Audit (SAEtestaudit2)", use_container_width=True):
        run_script("SAEtestaudit2.py")
        
    # Button for the 10-point Audit (baseSAE_sec_audit1.py)
    if st.button("Run 10-Point Base Audit", use_container_width=True):
        run_script("baseSAE_sec_audit1.py")
        
    st.markdown("---")
    st.subheader("🔐 Root Access Checks")
    
    # Button for Root MFA (ckrootmfa.py)
    if st.button("Check Root MFA Status", use_container_width=True):
        run_script("ckrootmfa.py")

    st.markdown("---")
    st.subheader("📐 Architecture Review")

    # NEW: Integration of SAEdiagrammar2.py
    if st.button("SAE Network Diagram Analyzer", use_container_width=True):
        run_script("SAEdiagrammar2.py")
        
        # Check for the JSON report generated by the diagrammar script
        report_file = "saenw_audit_report.json"
        if os.path.exists(report_file):
            with open(report_file, "rb") as file:
                st.download_button(
                    label="📥 Download Architecture JSON Report",
                    data=file,
                    file_name=report_file,
                    mime="application/json"
                )

# ================= COLUMN 2 =================
with col2:
    st.subheader("👥 IAM User Management")
    
    # Button for the complex user list (iamresearchscript.py)
    if st.button("Generate Detailed IAM User Report", use_container_width=True):
        run_script("iamresearchscript.py")
        # Check if the text file was created and offer download
        if os.path.exists("IAM-users.txt"):
            with open("IAM-users.txt", "rb") as file:
                st.download_button(
                    label="📥 Download IAM-users.txt",
                    data=file,
                    file_name="IAM-users.txt",
                    mime="text/plain"
                )

    # Button for group audit (chkiamusers.py)
    if st.button("Audit User Groups (CSV Export)", use_container_width=True):
        run_script("chkiamusers.py")
        # Check if the CSV was created and offer download
        if os.path.exists("aws_user_audit.csv"):
            with open("aws_user_audit.csv", "rb") as file:
                st.download_button(
                    label="📥 Download CSV Report",
                    data=file,
                    file_name="aws_user_audit.csv",
                    mime="text/csv"
                )

# --- Footer ---
st.markdown("---")
st.caption("SAE Test Flight 1 | Authorized Personnel Only")