#Requires -Version 5.1
<#
.SYNOPSIS
  One-command SAELAR install: unzip (if needed), install deps, create start script.
.DESCRIPTION
  Run from TestZippr or from anywhere with a SAELAR-distro-*.zip in current dir.
  To run:  install saelar   (use the install saelar.bat in this folder)
#>
param(
    [string]$TargetDir = "",   # Override install location
    [switch]$Start             # Start SAELAR after install
)

$ErrorActionPreference = "Stop"

# Where this script lives (expected: TestZippr)
$ScriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $ScriptRoot) { $ScriptRoot = Get-Location.Path }

function Find-Python {
    $py = $null
    foreach ($cmd in @("py", "python3", "python")) {
        try {
            $v = & $cmd -c "import sys; print(sys.executable)" 2>$null
            if ($v) { $py = $v.Trim(); break }
        } catch {}
    }
    return $py
}

function Get-AppDir {
    if ($TargetDir -and (Test-Path $TargetDir)) {
        $dir = Resolve-Path $TargetDir
        if (Test-Path (Join-Path $dir "nist_setup.py")) { return $dir }
    }

    # Prefer distro zip in script directory
    $zip = Get-ChildItem -Path $ScriptRoot -Filter "SAELAR-distro-*.zip" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($zip) {
        $extractTo = Join-Path $ScriptRoot "SAELAR"
        # Remove previous install at target for a fresh install
        if (Test-Path $extractTo) {
            Write-Host "[1/4] Removing previous install at $extractTo for clean install..." -ForegroundColor Yellow
            Remove-Item -Path $extractTo -Recurse -Force
        }
        New-Item -ItemType Directory -Path $extractTo -Force | Out-Null
        Write-Host "[1/4] Extracting $($zip.Name) to $extractTo ..." -ForegroundColor Cyan
        Expand-Archive -Path $zip.FullName -DestinationPath $extractTo -Force
        $appDir = $extractTo
        if (Test-Path (Join-Path $appDir "nist_setup.py")) { return (Resolve-Path $appDir).Path }
        # Zip might have flattened files at root
        return $appDir
    }

    # Use saelar_deploy if present
    $deploy = Join-Path $ScriptRoot "saelar_deploy"
    if (Test-Path (Join-Path $deploy "nist_setup.py")) {
        # Ensure risk_score modules are present
        foreach ($f in @("risk_score_app.py", "risk_score_calculator.py")) {
            $src = Join-Path $ScriptRoot $f
            $dst = Join-Path $deploy $f
            if ((Test-Path $src) -and -not (Test-Path $dst)) {
                Copy-Item -Path $src -Destination $dst -Force
                Write-Host "  Copied $f into saelar_deploy" -ForegroundColor Gray
            }
        }
        return (Resolve-Path $deploy).Path
    }

    # Current directory
    if (Test-Path (Join-Path (Get-Location) "nist_setup.py")) {
        return (Resolve-Path (Get-Location)).Path
    }

    throw "No SAELAR distro found. Put SAELAR-distro-*.zip in the same folder as this script, or run from TestZippr (saelar_deploy)."
}

Write-Host ""
Write-Host "  SAELAR - One-command install" -ForegroundColor Cyan
Write-Host ""

$pythonExe = Find-Python
if (-not $pythonExe) {
    Write-Host "Python not found. Install Python 3.8+ and ensure 'py' or 'python' is on PATH." -ForegroundColor Red
    exit 1
}
Write-Host "[1/4] Python: $pythonExe" -ForegroundColor Green

$appDir = Get-AppDir
Write-Host "[2/4] App dir: $appDir" -ForegroundColor Green

# Clean caches and leftover state for fresh run
foreach ($cache in @("__pycache__", ".streamlit")) {
    $cachePath = Join-Path $appDir $cache
    if (Test-Path $cachePath) {
        Remove-Item -Path $cachePath -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "  Cleared $cache" -ForegroundColor Gray
    }
}
Get-ChildItem -Path $appDir -Recurse -Directory -Filter "__pycache__" -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

$req = Join-Path $appDir "requirements.txt"
if (-not (Test-Path $req)) {
    Write-Host "requirements.txt not found in $appDir" -ForegroundColor Red
    exit 1
}
Write-Host "[3/4] Installing dependencies (pip install -r requirements.txt) ..." -ForegroundColor Cyan
& $pythonExe -m pip install --upgrade pip -q
& $pythonExe -m pip install -r $req -q
if ($LASTEXITCODE -ne 0) {
    Write-Host "pip install failed." -ForegroundColor Red
    exit 1
}
Write-Host "  Dependencies OK." -ForegroundColor Green

# Create start script in app dir (portable: uses its own folder)
$startPs1 = @"
# SAELAR start script (generated by install_saelar.ps1)
Set-Location `$PSScriptRoot
`$port = if (`$env:SAELAR_PORT) { `$env:SAELAR_PORT } else { "8484" }
Write-Host "  SAELAR - NIST 800-53" -ForegroundColor Cyan
Write-Host "  http://localhost:`$port" -ForegroundColor Yellow
& "$pythonExe" -m streamlit run nist_setup.py --server.port `$port --server.address 0.0.0.0
"@
$startPath = Join-Path $appDir "start_saelar.ps1"
Set-Content -Path $startPath -Value $startPs1 -Encoding UTF8
Write-Host "[4/4] Created $startPath" -ForegroundColor Green

Write-Host ""
Write-Host "  Install complete." -ForegroundColor Green
Write-Host "  To start SAELAR:" -ForegroundColor White
Write-Host "    cd `"$appDir`"" -ForegroundColor Gray
Write-Host "    .\start_saelar.ps1" -ForegroundColor Gray
Write-Host ""
Write-Host "  To run 'install saelar' from anywhere, add this folder to PATH:" -ForegroundColor Gray
Write-Host "    $ScriptRoot" -ForegroundColor Gray
Write-Host ""

if ($Start) {
    Write-Host "  Starting SAELAR ..." -ForegroundColor Cyan
    Set-Location $appDir
    & $startPath
}
