# Remediation Script for AD-004: Password Policy Enforcement
# Family: Identification & Authentication
# Generated by OPRA

# Step 1: Review current password policy
Get-ADDefaultDomainPasswordPolicy

# Step 2: Update Default Domain Policy password settings
Set-ADDefaultDomainPasswordPolicy -Identity 'domain.com' -MinPasswordLength 14 -PasswordHistoryCount 24 -ComplexityEnabled $true -MaxPasswordAge '90.00:00:00' -MinPasswordAge '1.00:00:00'

# Step 3: Create Fine-Grained Password Policy for privileged accounts
New-ADFineGrainedPasswordPolicy -Name 'PrivilegedAccountPolicy' -Precedence 10 -MinPasswordLength 20 -PasswordHistoryCount 30 -ComplexityEnabled $true -MaxPasswordAge '60.00:00:00'

# Step 4: Apply FGPP to privileged groups
Add-ADFineGrainedPasswordPolicySubject -Identity 'PrivilegedAccountPolicy' -Subjects 'Domain Admins'
