# Remediation Script for AD-007: AdminSDHolder Protection
# Family: Access Control
# Generated by OPRA

# Step 1: Review AdminSDHolder permissions
Get-ACL 'AD:\CN=AdminSDHolder,CN=System,DC=domain,DC=com' | Format-List

# Step 2: Find accounts with adminCount=1
Get-ADUser -Filter {adminCount -eq 1} -Properties adminCount,memberOf | Select-Object Name,adminCount

# Step 3: Clear orphaned adminCount attributes
# Review and clear adminCount for users no longer in protected groups
