# Remediation Script for AD-001: Domain Admin Account Security
# Family: Access Control
# Generated by OPRA

# Step 1: Audit current Domain Admin membership
Get-ADGroupMember -Identity 'Domain Admins' | Select-Object Name, SamAccountName, Enabled | Export-CSV DomainAdmins.csv

# Step 2: Remove unnecessary accounts from Domain Admins
Remove-ADGroupMember -Identity 'Domain Admins' -Members '<username>' -Confirm:$false
