# Remediation Script for AD-009: Replication Security
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Check SYSVOL replication method
Get-ADDomainController -Filter * | Select-Object Name,@{N='SysvolReplication';E={(Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\DFSR\Parameters\SysVols\Seeding SysVols' -ErrorAction SilentlyContinue)}}
