# Remediation Script for AD-002: Service Account Management
# Family: Access Control
# Generated by OPRA

# Step 1: Inventory all service accounts
Get-ADServiceAccount -Filter * | Select-Object Name, Enabled, PasswordLastSet

# Step 2: Create KDS Root Key (if not exists)
Add-KdsRootKey -EffectiveTime ((Get-Date).AddHours(-10))

# Step 3: Create Group Managed Service Account
New-ADServiceAccount -Name 'gMSA_ServiceName' -DNSHostName 'gmsa.domain.com' -PrincipalsAllowedToRetrieveManagedPassword 'ServerGroup'

# Step 4: Install gMSA on target server
Install-ADServiceAccount -Identity 'gMSA_ServiceName'
