# Remediation Script for AD-003: Group Policy Security
# Family: Configuration Management
# Generated by OPRA

# Step 1: Export current GPO permissions
Get-GPO -All | ForEach-Object { Get-GPPermission -Guid $_.Id -All } | Export-CSV GPOPermissions.csv

# Step 2: Remove unauthorized GPO edit permissions
Set-GPPermission -Name 'GPO Name' -TargetName 'UnauthorizedGroup' -TargetType Group -PermissionLevel None

# Step 4: Implement GPO backup strategy
Backup-GPO -All -Path 'C:\GPOBackups'
