# Remediation Script for AD-005: Kerberos Configuration
# Family: Identification & Authentication
# Generated by OPRA

# Step 1: Check current Kerberos encryption types
Get-ADObject -Filter 'msDS-SupportedEncryptionTypes -like "*"' -Properties msDS-SupportedEncryptionTypes | Where-Object {$_.'msDS-SupportedEncryptionTypes' -band 4}

# Step 3: Find accounts vulnerable to Kerberoasting
Get-ADUser -Filter {ServicePrincipalName -ne '$null'} -Properties ServicePrincipalName | Select-Object Name, ServicePrincipalName

# Step 4: Ensure pre-authentication is required for all accounts
Get-ADUser -Filter {DoesNotRequirePreAuth -eq $true} | Set-ADUser -DoesNotRequirePreAuth $false
