# Remediation Script for AD-008: Trust Relationship Security
# Family: Access Control
# Generated by OPRA

# Step 1: List all trust relationships
Get-ADTrust -Filter * | Select-Object Name,Direction,TrustType,DisallowTransivity,SIDFilteringForestAware

# Step 3: Configure selective authentication
Set-ADTrust -Identity 'TrustName' -SelectiveAuthentication $true
