# Remediation Script for AD-006: LDAP Signing & Channel Binding
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Check current LDAP signing configuration
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters' -Name 'LDAPServerIntegrity' -ErrorAction SilentlyContinue

# Step 3: Enable LDAP channel binding
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters' -Name 'LdapEnforceChannelBinding' -Value 2
