# Remediation Script for CFG-009: Least Functionality Enforcement
# Family: Configuration Management
# Generated by OPRA

# Step 1: Audit running services
Get-Service | Where-Object Status -eq 'Running' | Export-Csv 'RunningServices.csv'

# Step 2: Disable unnecessary services
Set-Service -Name 'RemoteRegistry' -StartupType Disabled; Stop-Service 'RemoteRegistry'

# Step 3: Disable unnecessary Windows features
Get-WindowsOptionalFeature -Online | Where-Object State -eq 'Enabled' | Export-Csv 'EnabledFeatures.csv'
