# Remediation Script for CFG-003: Golden Image Management
# Family: Configuration Management
# Generated by OPRA

# Step 3: Automate monthly image updates
New-ScheduledTask -Action (New-ScheduledTaskAction -Execute 'C:\Scripts\Update-GoldenImage.ps1') -Trigger (New-ScheduledTaskTrigger -Weekly -DaysOfWeek Wednesday -WeeksInterval 4)
