# Remediation Script for CFG-004: Software Inventory Control
# Family: Configuration Management
# Generated by OPRA

# Step 3: Configure automated detection of unauthorized software
Get-WmiObject Win32_Product | Where-Object {$_.Name -notin (Get-Content 'C:\Config\ApprovedSoftware.txt')} | Export-Csv 'UnauthorizedSoftware.csv'
