# Remediation Script for CFG-001: Baseline Configuration Standards
# Family: Configuration Management
# Generated by OPRA

# Step 2: Create GPO templates from benchmarks
Import-GPO -BackupGpoName 'CIS_Win11_L1' -TargetName 'Workstation_Baseline' -Path 'C:\GPOBackups'
