# Remediation Script for CP-004: Backup Verification & Testing
# Family: Contingency Planning
# Generated by OPRA

# Step 1: Configure automated backup verification
Test-DbaLastBackup -SqlInstance 'SQLSERVER01' | Export-Csv 'BackupTest.csv'
