# Remediation Script for CRY-002: TLS Configuration
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Disable TLS 1.0/1.1
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server' -Name Enabled -Value 0
