# Remediation Script for CRY-009: Disk Encryption Key Escrow
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Configure BitLocker AD key escrow via GPO
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\FVE' -Name 'ActiveDirectoryBackup' -Value 1
