# Remediation Script for CRY-010: Random Number Generation
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Enable FIPS mode on Windows
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy' -Name 'Enabled' -Value 1
