# Remediation Script for CRY-003: Certificate Lifecycle Management
# Family: System & Communications Protection
# Generated by OPRA

# Step 2: Inventory all certificates
Get-ChildItem -Path Cert:\LocalMachine\My | Select-Object Subject, NotAfter, Issuer | Sort-Object NotAfter
