# Remediation Script for DAT-004: Encryption in Transit
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Disable TLS 1.0/1.1
# Registry or IIS Crypto tool

# Step 2: Enable SMTP TLS
Set-ReceiveConnector -RequireTLS $true
