# Remediation Script for ECS-010: External Email Marking
# Family: System & Information Integrity
# Generated by OPRA

# Step 1: Create mail flow rule for external tagging
New-TransportRule -Name 'External Email Banner' -FromScope NotInOrganization -PrependSubject '[EXTERNAL] '
