# Remediation Script for END-004: Application Whitelisting
# Family: Configuration Management
# Generated by OPRA

# Step 2: Generate default AppLocker rules
Get-AppLockerPolicy -Local | Format-List

# Step 3: Analyze audit logs for required applications
Get-AppLockerFileInformation -EventLog | Group-Object -Property PublisherName
