# Remediation Script for END-003: Host-based Firewall
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Check firewall status
Get-NetFirewallProfile | Select-Object Name, Enabled

# Step 3: Configure firewall rules via GPO
New-NetFirewallRule -DisplayName 'Block Inbound' -Direction Inbound -Action Block

# Step 4: Enable firewall logging
Set-NetFirewallProfile -LogFileName '%systemroot%\system32\LogFiles\Firewall\pfirewall.log' -LogMaxSizeKilobytes 4096 -LogAllowed True -LogBlocked True
