# Remediation Script for END-006: USB/Removable Media Control
# Family: Media Protection
# Generated by OPRA

# Step 1: Audit current USB policy
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR' -Name Start
