# Remediation Script for END-007: Full Disk Encryption
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Check BitLocker status
Get-BitLockerVolume | Select-Object MountPoint, EncryptionMethod, VolumeStatus, ProtectionStatus

# Step 3: Enable BitLocker with TPM+PIN
Enable-BitLocker -MountPoint 'C:' -EncryptionMethod XtsAes256 -TPMandPinProtector -Pin (ConvertTo-SecureString 'PIN' -AsPlainText -Force)

# Step 4: Backup recovery keys to AD
Backup-BitLockerKeyProtector -MountPoint 'C:' -KeyProtectorId (Get-BitLockerVolume -MountPoint 'C:').KeyProtector[0].KeyProtectorId
