# Remediation Script for END-005: Local Admin Rights
# Family: Access Control
# Generated by OPRA

# Step 1: Audit local admin group membership
Get-LocalGroupMember -Group 'Administrators' | Select-Object Name, ObjectClass

# Step 2: Remove users from local Administrators group
Remove-LocalGroupMember -Group 'Administrators' -Member 'DOMAIN\Username'
