# Remediation Script for IAM-002: Privileged Access Management
# Family: Access Control
# Generated by OPRA

# Step 1: Inventory privileged accounts
Get-ADGroupMember 'Domain Admins' | Select-Object Name, SamAccountName
