# Remediation Script for IAM-003: Role-Based Access Control
# Family: Access Control
# Generated by OPRA

# Step 2: Create AD security groups for roles
New-ADGroup -Name 'Role_Finance_ReadOnly' -GroupScope Global -GroupCategory Security
