# Remediation Script for IAM-004: Account Lifecycle Management
# Family: Access Control
# Generated by OPRA

# Step 4: Run orphaned account audit
Get-ADUser -Filter * -Properties LastLogonDate | Where-Object {$_.LastLogonDate -lt (Get-Date).AddDays(-90)}
