# Remediation Script for IAM-010: Identity Federation
# Family: Identification & Authentication
# Generated by OPRA

# Step 1: Audit federation trusts
Get-ADFSRelyingPartyTrust | Select-Object Name, Enabled, TokenLifetime

# Step 2: Update to secure algorithms
# Disable SHA-1, use SHA-256 minimum
