# Remediation Script for SAT-006: Personnel Termination Procedures
# Family: Personnel Security
# Generated by OPRA

# Step 2: Automate AD account disable on HR notification
Disable-ADAccount -Identity $TermUser; Set-ADUser $TermUser -Description 'Terminated $(Get-Date -Format yyyy-MM-dd)'
