# Remediation Script for SRV-002: Unnecessary Services Disabled
# Family: Configuration Management
# Generated by OPRA

# Step 1: List running services
Get-Service | Where-Object {$_.Status -eq 'Running'} | Select-Object Name, DisplayName, StartType

# Step 2: Disable SMBv1
Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol

# Step 3: Disable TLS 1.0/1.1
# Registry: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols

# Step 4: Stop and disable unnecessary services
Stop-Service -Name 'ServiceName' -Force; Set-Service -Name 'ServiceName' -StartupType Disabled
