# Remediation Script for SRV-005: Web Server Security
# Family: System & Communications Protection
# Generated by OPRA

# Step 3: Remove unnecessary IIS modules
Remove-WindowsFeature Web-DAV-Publishing
