# Remediation Script for SRV-004: File Server Permissions
# Family: Access Control
# Generated by OPRA

# Step 1: List all shares and permissions
Get-SmbShare | ForEach-Object { Get-SmbShareAccess -Name $_.Name }

# Step 2: Remove Everyone from shares
Revoke-SmbShareAccess -Name 'ShareName' -AccountName 'Everyone' -Force

# Step 3: Audit NTFS permissions
Get-Acl 'D:\Share' | Format-List

# Step 4: Enable Access-Based Enumeration
Set-SmbShare -Name 'ShareName' -FolderEnumerationMode AccessBased
