# Remediation Script for SRV-009: Server Certificate Management
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Inventory certificates
Get-ChildItem -Path Cert:\LocalMachine\My | Select-Object Subject, NotAfter, Thumbprint
