# Remediation Script for SRV-006: Email Server Security
# Family: System & Communications Protection
# Generated by OPRA

# Step 1: Configure TLS for connectors
Set-ReceiveConnector -Identity 'Internet' -RequireTLS $true
