# Remediation Script for VCS-005: VM Snapshot Management
# Family: Media Protection
# Generated by OPRA

# Step 1: Audit all active VM snapshots
Get-VM | Get-Snapshot | Where-Object {$_.Created -lt (Get-Date).AddHours(-72)} | Select-Object VM, Name, Created
