# Remediation Script for VM-008: Database Vulnerability Assessment
# Family: Risk Assessment
# Generated by OPRA

# Step 1: Run database vulnerability scanner
Invoke-SqlVulnerabilityAssessment -ServerInstance 'SQLSERVER01' -DatabaseName 'ALL'
