# Remediation Script for VM-001: Vulnerability Scanning Program
# Family: Risk Assessment
# Generated by OPRA

# Step 1: Install and configure vulnerability scanner
Install-Module -Name Nessus -Force; Start-NessusScan -Target '10.0.0.0/8' -Policy 'Full Audit'
