# Remediation Script for VM-003: Asset Discovery & Inventory
# Family: System & Information Integrity
# Generated by OPRA

# Step 1: Deploy network discovery tool
Install-WindowsFeature -Name NPAS; Enable-NetFirewallRule -DisplayGroup 'Network Discovery'
